### ISSUE TITLE
Teletype subcommand creation causes nil reference error

### ISSUE THREAD

**Issue by jschank** [piotrmurach/tty-file#5]
I cannot use teletype to create a subcommand of a command.
When I do I get an exception

```
> teletype add contacts phonelist --force                                                                                                                                    136ms
      create  spec/integration/contacts/phonelist_spec.rb
      create  spec/unit/contacts/phonelist_spec.rb
      create  lib/ddca/commands/contacts/phonelist.rb
      create  lib/ddca/templates/contacts/phonelist/.gitkeep
Traceback (most recent call last):
	10: from /Users/jschank/.asdf/installs/ruby/2.5.1/bin/teletype:23:in `<main>'
	 9: from /Users/jschank/.asdf/installs/ruby/2.5.1/bin/teletype:23:in `load'
	 8: from /Users/jschank/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/tty-0.8.1/exe/teletype:14:in `<top (required)>'
	 7: from /Users/jschank/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	 6: from /Users/jschank/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	 5: from /Users/jschank/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	 4: from /Users/jschank/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	 3: from /Users/jschank/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/tty-0.8.1/lib/tty/cli.rb:88:in `add'
	 2: from /Users/jschank/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/tty-0.8.1/lib/tty/commands/add.rb:131:in `execute'
	 1: from /Users/jschank/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/tty-file-0.6.0/lib/tty/file.rb:512:in `inject_into_file'
/Users/jschank/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/tty-file-0.6.0/lib/tty/file.rb:512:in `escape': no implicit conversion of nil into String (TypeError)
```
It doesn't matter if I try to define parameters or not. I met this problem when I tried a more complex call:
```
> teletype add contacts phone_list --desc "Color code the phone extension list" --args contacts_file extension_xslx
```

Ultimately resulted in the same exception, from the same place

**Comment by piotrmurach** [comment]
Thanks, John for reporting!

Does the `contacts` command already exist when you're trying to create `contacts phonelist` subcommand? Would it be possible for you to report this issue at https://github.com/piotrmurach/tty since that's where the `teletype` tool is developed?

**Comment by jschank** [comment]
Yep, contacts already existed. 
And I will repost this on TTY.

It might take me a bit to get to it (being a working day and all) 
Appreciate the quick reply - and I really like the work you've done here

**Comment by jschank** [comment]
Since this has moved to tty, I believe the next step would be to close this issue here. And let it live in the tty project
